### ISSUE TITLE
Llamar actualizarEstadoEnvios en listado de envios en web

### ISSUE THREAD

**Issue by dcorvetto** [2016AplicacionesDistribuidas/2016ADG04#204]
Para ver estado de los vehiculos (demorados, alerta, etc)

**Comment by vguccione** [comment]
No entiendo!!!!!!!!!

**Comment by dcorvetto** [comment]
En el backend , ListadoEnviosPropios y Tercerizados, se llama antes de cargar el listado al metodo
actualizarEstadoEnvios() . Lo que hace es  revisar automaticamente si el envio esta demorado o desviado/en alerta. Para demorado se fija la fecha estimada vs. la fecha actual. Para desviado buscar archivos y compara coordenadas, si existe desde ya un xml cargado.  Despues veo de agregarlo.
